[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.worker"

[deploy]
startCommand = "sh -c 'cd backend && uv run python worker.py'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = ""
healthcheckTimeout = 0